### ISSUE TITLE
Parsing semver is not working with lines like: '>= 0.3.0 < 0.4.0"

### ISSUE THREAD

**Issue by illuusio** [marguerite/rubygem-node2rpm#4]
This one throws error like:
```
/usr/lib64/ruby/gems/2.4.0/gems/node2rpm-1.0.0/lib/node2rpm/dependency.rb:33:in `block in get_dependency': jsdom's dependency cssom has nil-matched version! Raw version range: >= 0.3.0 < 0.4.0. All available versions: ["0.2.0", "0.2.1", "0.2.2", "0.2.3", "0.2.4", "0.2.5", "0.3.0", "0.3.1", "0.3.2"]. Usually it means you need to clear your cache at /tmp/node2rpm. (Node2RPM::Exception)
        from /usr/lib64/ruby/gems/2.4.0/gems/node2rpm-1.0.0/lib/node2rpm/dependency.rb:28:in `each'
        from /usr/lib64/ruby/gems/2.4.0/gems/node2rpm-1.0.0/lib/node2rpm/dependency.rb:28:in `get_dependency'
        from /usr/lib64/ruby/gems/2.4.0/gems/node2rpm-1.0.0/lib/node2rpm/dependency.rb:16:in `dependencies'
        from /usr/lib64/ruby/gems/2.4.0/gems/node2rpm-1.0.0/lib/node2rpm/tree.rb:23:in `generate'
        from /usr/lib64/ruby/gems/2.4.0/gems/node2rpm-1.0.0/lib/node2rpm/tree.rb:32:in `block (2 levels) in generate'
        from /usr/lib64/ruby/gems/2.4.0/gems/node2rpm-1.0.0/lib/node2rpm/tree.rb:31:in `each'
        from /usr/lib64/ruby/gems/2.4.0/gems/node2rpm-1.0.0/lib/node2rpm/tree.rb:31:in `block in generate'
        from /usr/lib64/ruby/gems/2.4.0/gems/node2rpm-1.0.0/lib/node2rpm/tree.rb:87:in `generate'
        from /usr/lib64/ruby/gems/2.4.0/gems/node2rpm-1.0.0/lib/node2rpm/tree.rb:32:in `block (2 levels) in generate'
        from /usr/lib64/ruby/gems/2.4.0/gems/node2rpm-1.0.0/lib/node2rpm/tree.rb:31:in `each'
        from /usr/lib64/ruby/gems/2.4.0/gems/node2rpm-1.0.0/lib/node2rpm/tree.rb:31:in `block in generate'
        from /usr/lib64/ruby/gems/2.4.0/gems/node2rpm-1.0.0/lib/node2rpm/tree.rb:42:in `generate'
        from /usr/lib64/ruby/gems/2.4.0/gems/node2rpm-1.0.0/lib/node2rpm.rb:12:in `generate'
        from /usr/lib64/ruby/gems/2.4.0/gems/node2rpm-1.0.0/bin/node2rpm:80:in `<top (required)>'
        from /usr/bin/node2rpm:22:in `load'
        from /usr/bin/node2rpm:22:in `<main>'
```
Line parsed is: ">=.0.0", "=0.3.0", "<.0.0", "=0.4.0" as expected from code but this cannot be satisfied anyhow.

**Comment by illuusio** [comment]
fstream also have this kind depency: '>=0.5 0' which probably is 0.5.0

**Comment by illuusio** [comment]
I also fixed this one.. Do you want PR or fix yourself?

**Comment by marguerite** [comment]
please send a PR and we can talk about that:)

there are two way to fix it. The first is to treat this as a special case in node_semver, the second is to add a pre-fix script to nodejs-packaging so packager can correct it in prep section of specfile.

I was thinking which one is better...

**Comment by marguerite** [comment]
fixed
