### ISSUE TITLE
Yarn generates problem

### ISSUE THREAD

**Issue by illuusio** [marguerite/rubygem-node2rpm#5]
Yarn pacakge building  at https://build.opensuse.org/package/show/home:illuusio:nodejs-bundle/yarn doesn't work:

```
[   33s] /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/lib/node2rpm/server.rb:377:in `clean_empty_directories': private method `select' called for nil:NilClass (NoMethodError)
[   33s] 	from /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/lib/node2rpm/server.rb:74:in `clean'
[   33s] 	from /usr/lib64/ruby/gems/2.1.0/gems/node2rpm-1.0.0/bin/node2rpm-server:19:in `<top (required)>'
[   33s] 	from /usr/bin/node2rpm-server:23:in `load'
[   33s] 	from /usr/bin/node2rpm-server:23:in `<main>'
[   33s] error: Bad exit status from /var/tmp/rpm-tmp.DoFTPH (%build)
```

**Comment by marguerite** [comment]
Fixed
